name: Build Bootloader

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '9-2020-q2'

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Build
        run: |
          mkdir -p output
          for board_dir in boards/*; do
            board=$(basename $board_dir)
            ./clean.sh && ./build.sh ${board}
            mv build/bootloader.hex output/bootloader-${board}.hex
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bootloader
          path: output
          if-no-files-found: error

  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: bootloader

      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: '*.hex'
          file_glob: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
